import {useState} from 'react'
import Link from 'next/link'
import Head from 'next/head'
import { useSession, signIn, signOut } from 'next-auth/react'
import {ImCart} from "react-icons/im"
import {BsBookHalf} from "react-icons/bs"
import { useAppStateContext } from '../utilis/AppStateProvider'
import { client } from '../sanity/client'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import {BsLayoutSidebarInset} from "react-icons/bs"
import SidebarV2 from './smallScreen/SidebarV2'
import CartMenu from './CartMenu'
import Sidebar from './Sidebar'
import {MdSearch} from "react-icons/md"
import Footer from './Footer'

const Layout = ({children}) => {
    const {data: session} = useSession()
    const [showMenu, setShowMenu] = useState(false)
    const [showCart, setShowCart] = useState(false)
    const [sideMenu, setSideMenu] = useState(false)
    const [searchTerm, setSearchTerm] = useState("")
    const {cartLength, setCartLength} = useAppStateContext()
    const router = useRouter()
    const slug = router.asPath
    useEffect(() => {
        if (session) {
            client.fetch(`*[_type == "user" && _id == '${session?.user?.id}'] {cart}`).then(data => data[0].cart && setCartLength(data[0].cart.length)).catch(err => console.log(err))
        }
        
    }, [session])
    useEffect(() => {
        setShowMenu(false)
        setShowCart(false)
    }, [slug])

    const toggleMenu = (menu) => {
        if (menu === "menu") {
            setShowCart(false)
            setSideMenu(false)
            setShowMenu(!showMenu)
        } else if (menu === "sideMenu") {
            setShowMenu(false)
            setShowCart(false)
            setSideMenu(!sideMenu)
        } else if (menu === "cart") {
            setShowMenu(false)
            setSideMenu(false)
            setShowCart(prevState => !prevState)
        }
    }
    const onSearch = (searchTerm) => {
        setSearchTerm(searchTerm)
        router.push(`/books/search/${searchTerm}`)
    }

  return (
    <div>
        <Head>
            <title>Bookstore</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/faviconBS.png" />
        </Head>
        <div className="flex items-center justify-between bg-slate-900 text-white px-5 py-3">
            <Link href="/">
                <div className="flex gap-1 items-center">   
                    <BsBookHalf className="w-6 h-6" />
                    <p className="text-lg font-semibold">Bookstore</p>
                </div>
            </Link>
            <div className="bg-white flex items-center searchbar">
                <input placeholder="Search" onChange={(e) => onSearch(e.target.value)} className="searchbar text-black w-[450px] p-1  outline-none" type="text" />
                <div className="text-black pr-1">
                    <button type="button" className="flex items-center"><MdSearch onClick={() => onSearch(searchTerm)} className="w-6 h-6 " /></button>
                </div>
            </div>
            {session ? (
                <nav>
                    <ul className="flex gap-10 items-center">
                        <li onClick={() => toggleMenu("cart")} className=" cartLogo flex gap-1 cursor-pointer">
                            <p className="font-bold text-amber-300">{cartLength}</p>
                            <ImCart className="w-6 h-6 " />
                        </li>
                        <div className="w-px h-6 bg-white cartLogo "></div>
                        <li onClick={() => toggleMenu("menu")} className="cursor-pointer">
                           <img src={session.user.image} className="w-8 h-8 rounded-full border border-slate-400" />
                        </li>
                        
                    </ul>
                </nav>
            ) : <button className="font-semibold flex gap-1 items-center" type="button" onClick={() => signIn()}>Sign in <img src="/login.svg" className="w-5 h-5 text-white" /></button>}
        </div>
        <div className="flex gap-6border-b border-t border-black py-2 bg-slate-800 text-white">
            <nav className="w-full mx-5 flex gap-10 justify-between items-center text-sm">
                <ul className="flex gap-10">
                    <li>
                       <p className="font-semibold hover:text-amber-300 cursor-pointer">Today Deals</p>
                    </li>
                    <li>
                       <p className="font-semibold hover:text-amber-300 cursor-pointer">Gift Cards</p>
                    </li>
                    <li>
                       <p className="font-semibold hover:text-amber-300 cursor-pointer">Best Sellers</p>
                    </li>
                    
                </ul>
                <ul className="flex gap-10">
                    <li>
                       <Link href="/account/booklist" className="font-semibold hover:text-amber-300 cursor-pointer">My Book List</Link>
                    </li>
                    <li>
                       <Link href="/account/cart" className="font-semibold hover:text-amber-300 cursor-pointer">View Cart</Link>
                    </li>
                </ul>
            </nav>
        </div>
        {/* small screen <-V-> */}
        <div className="secondNavbar flex gap-6border-b border-t border-black py-3 bg-slate-800 text-white">
            <nav className="w-full mx-5">
                <ul className="flex gap-10 justify-between items-center w-full">
                    <li>
                        <button onClick={() => toggleMenu("sideMenu")} className="">
                            <BsLayoutSidebarInset className="text-white w-6 h-6 text-slate-900" />
                        </button>
                    </li>
                        <input placeholder="Search" className="text-black w-full px-2 py-[1px] outline-none" type="text" onChange={() => {}} />
                    <li onClick={() => toggleMenu("cart")} className="flex gap-1 cursor-pointer">
                        <p className="font-bold text-amber-300">{cartLength}</p>
                        <ImCart className="w-6 h-6" />
                    </li>
                </ul>
            </nav>
        </div>
        {showMenu && (
            <div className="absolute right-0 top-13 bg-slate-100 border shadow-md px-1 py-1" >
                <ul>
                    <li className="border-b border-slate-300 py-2 px-2">
                        <div className="flex gap-2 items-center">
                            <div>
                                <img className="w-10 h-10 rounded-full border border-slate-400" src={session.user.image} />
                            </div>
                            <div>
                                <p className="font-semibold">{session.user.name}</p>
                                <p className="text-sm">{session.user.email}</p>
                            </div>
                        </div>
                    </li>
                    <li className="border-b border-slate-300 py-2 px-2 hover:bg-slate-200 cursor-pointer ">
                        <Link className="" href="/">Account</Link>
                    </li>
                    <li className="border-b border-slate-300 py-2 px-2 hover:bg-slate-200 cursor-pointer ">
                        <Link className="" href="/">Settings</Link>
                    </li>
                    <li className="border-b border-slate-300 py-2 px-2 hover:bg-slate-200 cursor-pointer ">
                        <Link className="" href="/">Help</Link>
                    </li>
                    <li className=" py-2 px-2 hover:bg-slate-200 ">
                        <button className="text-black" type="button" onClick={() => signOut()}>Sign out</button>
                    </li>
                </ul>
            </div>
        )}
        {showCart && ( <>
            <CartMenu session={session}  />
        </>)}
        <main className="min-h-[100vh] mb-6">
            <div className="flex h-full">
                <Sidebar />
                {sideMenu && <SidebarV2 />}
                
                <div className="w-full">
                    {children}
                </div>
            </div>
        </main>
        <Footer />
    </div>

  )
}

export default Layout